apiVersion: v1 
kind: Service 
metadata:
  name: test-load-balancer
  labels:
    environment: test
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector: 
    app: vaea-rest-test
